version: '3.8'

services:
  md2any:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "5002:5002"
    volumes:
      - ./themes:/app/themes
    environment:
      - FLASK_ENV=development