version: '3.8'

services:
  md2any:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
    # Only mount the themes directory if you need to override CSS files
    # Comment out the volumes section if you don't need to override files
    # volumes:
    #   - ./themes:/app/themes:ro