version: '3.8'

services:
  md2any:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped