# Override file for local development
# This file is automatically loaded by docker-compose
version: '3.8'

services:
  md2any:
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python api_server.py