version: '3.8'

services:
  md2any:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # WeChat API configuration (optional - can be set via API calls)
      # - WECHAT_APPID=your_wechat_appid
      # - WECHAT_SECRET=your_wechat_secret